### ISSUE TITLE
Add dependency version information to a central file

### ISSUE THREAD

**Issue by eureka-cpu** [bonsol-collective/bonsol#89]
The project depends on quite a lot of dependencies to be present, it would be nice to just have them declared somewhere similarly to the rust-toolchain.toml

I'd prefer it if it were a toml file, and to be frank having another toolchain file sort of feels like bloat. IMO we could just use the rust-toolchain.toml to add extra tables to represent the dependencies we don't already manage via the root Cargo.toml (if any). Otherwise I'd be fine with just writing a function for the nix side of things to get the versions from there. The rust-toolchain.toml only looks for certain tables and fields so adding explicit ones won't affect anything else. Something like:

```toml
# rust-toolchain.toml
[toolchain]
channel = "X.X.X"
components = ["rustfmt", "clippy", "rust-analyzer"]

[toolchain.flatc]
version = "24.3.25"
hash = "sha256-uE9CQnhzVgOweYLhWPn2hvzXHyBbFiFVESJ1AEM3BmA="

[toolchain.risc0-groth16-prover]
version = "v2024-05-17.1"
hash = "sha256-SV8nUjtq6TheYW+vQltyApOa7/gxnBrWx4Y6fQ71LFg="

# etc
```

Open to suggestions.
Ref #29
